image:
  file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
tasks:
  - name: Insatll BashHub
    command: cd /workspace && curl -OL https://bashhub.com/setup && bash setup && rm setup
  - name: Run phpMyAdmin
    command: cd /workspace/phpMyAdmin-5.2.0-all-languages && sudo php -S 0.0.0.0:80
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true