image:
  file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
tasks:
  - name: "Insatll BashHub"
    init: "curl -OL https://bashhub.com/setup && bash setup"
