image:
  file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - name: VNC
    description: full GUI Virtual Desktop
    port: 6080
    onOpen: open-browser
  - name: phpMyAdmin
    port: 80
    onOpen: open-browser  
tasks:
  - name: Insatll & Configure BashHub
    command: |
      eval $(gp env -e)
      echo $BASH_HUB_ACCESS_TOKEN \
        && echo $BASH_HUB_SYSTEM_NAME \
        && bashHubConfigurationFolder=$HOME/.bashhub \
        && bashHubConfigurationFile=config \
        && mkdir $bashHubConfigurationFolder \
        && bashHubConfigurationPath=$bashHubConfigurationFolder/$bashHubConfigurationFile \
        && printf "[bashhub]\naccess_token = $(echo $BASH_HUB_ACCESS_TOKEN)\nsystem_name = $(echo $BASH_HUB_SYSTEM_NAME)" > $bashHubConfigurationPath \
        && cat $bashHubConfigurationPath \
        && cd /workspace \
        && curl -OL https://bashhub.com/setup \
        && bash setup \
        && rm setup
  - name: Run phpMyAdmin
    command: cd /opt/phpMyAdmin-5.2.0-all-languages && sudo php -S 0.0.0.0:80
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
jetbrains:
  intellij:
    prebuilds:
      version: both
  goland:
    prebuilds:
      version: both
  pycharm:
    prebuilds:
      version: both
  phpstorm:
    prebuilds:
      version: both
vscode:
  extensions:
    - vscode.markdown
    - vscode.markdown-language-features
    - vscode.github
    - GitHub.vscode-pull-request-github
    - vscode.merge-conflict
    - vscode.references-view
    - vscode.search-result
    - vscode.docker
    - redhat.vscode-yaml
    - vscode.json