image:
  file: .gitpod.Dockerfile

ports:
  - port: 5900
    onOpen: ignore
  - port: 45767
    onOpen: ignore
  - name: VNC
    description: full GUI Virtual Desktop
    port: 6080
    onOpen: open-browser

tasks:
  - name: Initialize Workspace
    command: bash workspaceInitialize.bash

# - name: Open Google Chrome
#   command: bash launchGoogleChrome.bash

jetbrains:
  intellij:
    prebuilds:
      version: both
  goland:
    prebuilds:
      version: both
  pycharm:
    prebuilds:
      version: both
  phpstorm:
    prebuilds:
      version: both