image:
  file: .gitpod.Dockerfile

ports:
  - port: 5900
    onOpen: ignore
  - name: VNC
    description: full GUI Virtual Desktop
    port: 6080
    onOpen: open-browser
  - name: phpMyAdmin
    port: 80
    onOpen: open-browser  

tasks:
  - name: Initialize Workspace
    command: bash workspaceInitialize.bash

# - name: Setup JADX & dex2jar
#   command: |
#     echo "export PATH=$HOME/$(cat $HOME/dexToolsFolder):$HOME/$(cat $HOME/dexToolsFolder)/bin:$HOME/$(cat $HOME/jadxFolder)/bin:$PATH" >> ~/.bashrc \
#     && rm $HOME/dexToolsFolder $HOME/jadxFolder \
#     && source ~/.bashrc

# - name: Open Google Chrome
#   command: bash launchGoogleChrome.bash

# - name: Open Eclipse
#   command: cd /usr/local/eclipse/ && ./eclipse

# - name: Open Android Studio Canary
#   command: cd /workspace && git clone --depth 1 "https://gitlab.com/baneeishaque/gitpod-workspace-full-vnc-1366x768-tint2-pcmanfm-zsh-android-studio.git" android-studio-config && rm -rf ~/.config/Google && mkdir -p ~/.config/Google && ln -s `pwd`/android-studio-config/AndroidStudioPreview2022.1-config ~/.config/Google/AndroidStudioPreview2022.1 && rm -rf ~/.local/share/Google && mkdir -p ~/.local/share/Google && ln -s `pwd`/android-studio-config/AndroidStudioPreview2022.1-local ~/.local/share/Google/AndroidStudioPreview2022.1 && rm -rf ~/.local/share/Google/consentOptions && ln -s `pwd`/android-studio-config/consentOptions ~/.local/share/Google/consentOptions && cd /usr/local/android-studio-canary/bin/ && ./studio.sh

# - name: Open Android Studio Beta
#   command: cd /workspace && git clone --depth 1 "https://gitlab.com/baneeishaque/gitpod-workspace-full-vnc-1366x768-tint2-pcmanfm-zsh-android-studio.git" android-studio-config && rm -rf ~/.config/Google && mkdir -p ~/.config/Google && ln -s `pwd`/android-studio-config/AndroidStudio2021.3-config ~/.config/Google/AndroidStudio2021.3 && rm -rf ~/.local/share/Google && mkdir -p ~/.local/share/Google && ln -s `pwd`/android-studio-config/AndroidStudio2021.3-local ~/.local/share/Google/AndroidStudio2021.3 && cd /usr/local/android-studio-beta/bin/ && ./studio.sh

# - name: Get Gist
#   command: getgist <username> <filename>

# - name: List Gists
#   command: lsgists <username>

# - name: Check Poetry
#   command: poetry --version

# - name: Check VS Code Insiders
#   command: code-insiders --version

# - name: Setupe Edge
#   command: cd /workspace && rm -rf /workspace/microsoft-edge-config-private && git clone $(echo $EDGE_CONFIGURATION_REPOSITORY_URL) && cd /workspace && rm -rf ~/.config/microsoft-edge-dev && ln -s `pwd`/microsoft-edge-config-private/microsoft-edge-dev ~/.config/microsoft-edge-dev

# - name: Run Squid Proxy Server
#   command: sudo service squid restart && sudo service squid status

jetbrains:
  intellij:
    prebuilds:
      version: both
  goland:
    prebuilds:
      version: both
  pycharm:
    prebuilds:
      version: both
  phpstorm:
    prebuilds:
      version: both